---
- name: Add ppa Repository
  become: yes
  become_method: sudo
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Install php
  become: yes
  become_method: sudo
  apt: pkg={{ php.version }} state=latest

- name: Install php-fpm
  become: yes
  become_method: sudo
  apt: pkg={{ php.version }}-fpm state=latest

- name: Install PHP Packages
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=latest
  with_items: "{{ php.packages }}"
  when: php.packages is defined

- include: configure.yml
